spring.application.name=product-service
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=test1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Opcional: desactiva Flyway temporalmente si no tienes migraciones configuradas
spring.flyway.enabled=false

